FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Expose port (optional, only for documentation, docker-compose handles mapping)
EXPOSE 3000

CMD ["npm", "run", "dev"]